# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d761061a4ec0115f6fb66d3beb4e05a318fa9b031407ae008a74a7ee7822e0d3f73c8cc409d6c42518d06c2afab89de3086f1464eb7d8cef1335d983eff662

test:
  secret_key_base: aae173a9da50790d8a6ee01acf165e0c3d7ee032ac46f99d230ce72caee0d79877efc6b1c09fef273df03eacf0e8e155163955568990c7b584d66ff53cedaf6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
